VideoClubA.Web/Areas/ActiveReservations/Controllers/ActiveReservationController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using VideoClubA.Core.Entities;
using VideoClubA.Core.Interfaces;
using VideoClubA.Web.Areas.ActiveReservations.Models;

namespace VideoClubA.Web.Areas.ActiveReservations.Controllers
{
    public class ActiveReservationController : Controller
    {

        private readonly IMovieRentService _movieRentDb;
        private readonly ICustomerSevice _customerDb;
        private readonly IMovieCopyService _movieCopyDb;
        private readonly IMapper _mapper;

        public ActiveReservationController(IMovieRentService movieRentDb,
            ICustomerSevice customerDb, IMovieCopyService movieCopyDb,
            IMapper mapper)
        {
            _movieRentDb = movieRentDb;
            _customerDb = customerDb;
            _movieCopyDb = movieCopyDb;
            _mapper = mapper;
        }

        [HttpGet]
        [Area("ActiveReservations")]
        [Authorize(Policy = "AdminOnly")]
        public IActionResult ActiveReservationsPanel(int page = 1, int pageSize = 5)
        {

            return View(PaginateReservations(page, pageSize));
        }

        private ActiveReservationsViewModel PaginateReservations(int page, int pageSize)
        {

            //Validate Page
            page = Math.Clamp(page, 1, pageSize);

            int startIndex = (int)((page - 1) * pageSize);

            List<MovieRent> allReservations = _movieRentDb.GetMovieRents();

            var activeReservations = _mapper.Map<List<ActiveReservationViewModel>>
                (allReservations);

            int totalPages = (int)Math.Ceiling((double)activeReservations.Count / pageSize);

            activeReservations = activeReservations.Skip(startIndex).Take(pageSize).ToList();


            var reservationsViewModel = new ActiveReservationsViewModel(
                activeReservations, page);


            reservationsViewModel.CurrentPage = page;
            reservationsViewModel.TotalPages = totalPages;

            return reservationsViewModel;

        }
    }
}

VideoClubA.Web/Areas/Customers/Controllers/CustomerController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using VideoClubA.Core.Interfaces;
using VideoClubA.Web.Areas.Customers.Models;
using VideoClubA.Web.Areas.Movies.Controllers;

namespace VideoClubA.Web.Areas.Customers.Controllers
{
    public class CustomerController : Controller
    {
        private readonly ILogger _logger;
        private readonly ICustomerSevice _customerDb;
        private readonly IMovieRentService _movieRentDb;

        public CustomerController( ICustomerSevice customerDb, IMovieRentService movieRentDb,
            ILogger<MovieController> logger)
        {
            _logger = logger;
            _customerDb = customerDb;
            _movieRentDb = movieRentDb;

        }


        [HttpGet]
        [Area("Customers")]
        [Authorize(Policy = "AdminOnly")]
        public ActionResult CustomerPanel(int page = 1, int pageSize = 5)
        {
            return View(PaginateCustomer(page, pageSize));
        }

        private CustomersWithActiveReservationViewModel PaginateCustomer(int page, int pageSize)
        {

            //Validate Page
            page = Math.Clamp(page, 1, pageSize);

            int startIndex = (int)((page - 1) * pageSize);

            var customersWithActiveReservations = new MovieRentCustomer(_customerDb, _movieRentDb).Get();


            int totalPages = (int)Math.Ceiling((double)customersWithActiveReservations.Count / pageSize);
            
            customersWithActiveReservations = customersWithActiveReservations.Skip(startIndex).Take(pageSize).ToList();


            var customersViewModel = new CustomersWithActiveReservationViewModel(
                customersWithActiveReservations, page);


            customersViewModel.CurrentPage = page;
            customersViewModel.TotalPages = totalPages;

            return customersViewModel;
        }

    }
}
 

VideoClubA.Web/Areas/Movies/Controllers/MovieController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using VideoClubA.Core.Entities;
using VideoClubA.Core.Interfaces;
using VideoClubA.Web.Areas.Movies.Models;

namespace VideoClubA.Web.Areas.Movies.Controllers
{
    public class MovieController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IMovieService _movieDb;
        private readonly IMovieCopyService _movieCopyDb;
        private readonly ILogger _logger;

        public MovieController(IMapper mapper, IMovieService movieDb, IMovieCopyService movieCopyDb,
            ILogger<MovieController> logger)
        {
            _mapper = mapper;
            _movieDb = movieDb;
            _movieCopyDb = movieCopyDb;
            _logger = logger;
        }

        [HttpGet]
        [Area("Movies")]
        public ActionResult MovieGallery(int page = 1, int pageSize = 5, string searchString = "", string filter = "")
        {
    
           return View(PaginateMovies(page, pageSize, searchString, filter));
         
        }

        private Dictionary<string, int> GetAllAvailabilityPerMovie()
        {
            List<MovieCopy> availableMoviesCopies = _movieCopyDb.GetAllAvailabiliy();

            var movieCopyIds = availableMoviesCopies.GroupBy(c => c.MovieId);

            var result = movieCopyIds.ToDictionary(g => g.Key, g => g.Count());

            return result;
        }

        private MoviesWithAvailabilityViewModel PaginateMovies(int page, int pageSize,
             string searchString,  string filter)
        {

            //Validate Page
            page = Math.Clamp(page, 1, pageSize);

            int startIndex = (int)((page - 1) * pageSize);

            List<Movie> movies = _movieDb.GetAllMovies();

            Dictionary<string, int> availabilityPerMovie = GetAllAvailabilityPerMovie();

            int totalPages = (int)Math.Ceiling((double)movies.Count / pageSize);

            var moviesList = _mapper.Map<List<MovieWithAvailabilityViewModel>>
                (movies.OrderBy(m => m.Title), opt => opt.Items["AvailabilityPerMovie"] = availabilityPerMovie);

            List<MovieWithAvailabilityViewModel> movieResults;


            if (!string.IsNullOrEmpty(searchString))
            {
                //Search
                movieResults = moviesList.Where(s => s.Title.Contains(searchString)).ToList();
            }
            else if (!string.IsNullOrEmpty(filter))
            {
                //Filter
                movieResults = moviesList.Where(s => s.Genre.ToString().Equals(filter)).ToList();
            }
            else
            {
                movieResults = moviesList;
            }

            movieResults = movieResults.Skip(startIndex).Take(pageSize).ToList();

            var moviesViewModel = new MoviesWithAvailabilityViewModel(
                movieResults.ToList(),page,searchString,filter);


            moviesViewModel.CurrentPage = page;
            moviesViewModel.TotalPages = totalPages;
            moviesViewModel.SearchString = searchString;
            moviesViewModel.Filter = filter;

            return moviesViewModel;
        }


    }
}

VideoClubA.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - VideoClubA.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
     <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/VideoClubA.Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/cyborg.css" />

</head>
<body>
   
        <div class="container">
            <div class="row">
                <div class="col">
                     <header>
                    <nav class="navbar navbar-expand-lg navbar-light bg-light">
                      <div class="container-fluid">
                        <a class="navbar-brand" href="#">Video Club</a>
                        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                          <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="collapse navbar-collapse" id="navbarColor01">
                          <ul class="navbar-nav me-auto">
                            <li class="nav-item">
                              <a class="nav-link active" href="#">Home
                                <span class="visually-hidden">(current)</span>
                              </a>
                            </li>
                            <li class="nav-item">
                              <a class="nav-link" asp-area="Movies" asp-controller="Movie" asp-action="MovieGallery">Ταινίες</a>
                            </li>
                            <li class="nav-item">
                               <a  class="nav-link" asp-area="Customers" asp-controller="Customer" asp-action="CustomerPanel">Πελάτες</a>
                            </li>
                            <li class="nav-item">
                               <a class="nav-link" asp-area="ActiveReservations" asp-controller="ActiveReservation" asp-action="ActiveReservationsPanel">Ενεργές Κρατήσεις</a>

                            </li>
                             <li class="nav-item">
                               <a class="nav-link" asp-area="Accounts" asp-controller="Account" asp-action="Index">Login</a>

                            </li>
                          </ul>
                        </div>
                      </div>
                    </nav>
                   </header>
                    <main role="main" class="pb-3" style="background-color:black">
                        @RenderBody()
                    </main>
                 <footer class="border-top footer text-muted">
                    <div class="container">
                        &copy; 2023 - VideoClubA.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </div>
                </footer>
                    <script src="~/lib/jquery/dist/jquery.min.js"></script>
                    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
                    <script src="~/js/site.js" asp-append-version="true"></script>
                    @await RenderSectionAsync("Scripts", required: false)
                </body>
                </div>
            </div>
        </div>


       


</html>